export default [
  { title: "pasta" },
  { title: "pizza" },
  { title: "pie" },
  { title: "Chicken" },
  { title: "cack" },
  { title: "rolls" },
  { title: "ice cream" },
  { title: "Oatmeal Cookies" },
  { title: "sea food" },
  { title: "bread" },
  { title: "Noodles" },
  { title: "nutella" },
  { title: "mushroom" },
];
